<?php
/**
 * Extend Warranty
 *
 * Guidance Magento Team <magento@guidance.com>
 * Copyright (c) 2022 Guidance Solutions (http://www.guidance.com)
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isExtendEnabled()): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig(); ?>
    <?php if ($jsonConfig): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "extendInstallment": {
                    "libURL": "<?= $block->escapeJs($viewModel->getJsMode()) ?>",
                    "config": <?= /* @noEscape */ $jsonConfig ?>
                }
            }
        }
        </script>

        <?php if ($block->getTrackingEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "extendTrackingService": {}
            }
        }
        </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
