<?php
/**
 * Extend Warranty
 *
 * Guidance Magento Team <magento@guidance.com>
 * Copyright (c) 2022 Guidance Solutions (http://www.guidance.com)
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Extend\Warranty\ViewModel\Installation $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php if ($viewModel->isExtendEnabled()): ?>
    <?php $jsonConfig = $viewModel->getJsonConfig(); ?>
    <?php if ($jsonConfig): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "extendInstallment": {
                    "libURL": "<?= $block->escapeJs($viewModel->getJsMode()) ?>",
                    "config": <?= /* @noEscape */ $jsonConfig ?>
                }
            }
        }
        </script>

        <script>
            /*require.config({
                config: {
                    mixins: {
                        'Magento_Checkout/js/view/minicart': {
                            'Extend_Warranty/js/view/minicart-mixin': true
                        },
                        'Magento_Checkout/js/sidebar': {
                            'Extend_Warranty/js/sidebar-mixin': true
                        }
                    }
                }
            });*/
        </script>

        <?php if ($block->getTrackingEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Extend_Warranty/js/tracking-service": {}
            }
        }
        </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
